### ISSUE TITLE
Graphviz image update

### ISSUE THREAD

**Issue by quasiben** [ContinuumIO/odo#124]
It's entirely cosmetic, but the graphviz network should be updated with `odo` -- perhaps there is some new functionality which could be merged into the network?

**Comment by cpcloud** [comment]
@quasiben I'm not sure what you mean here. Are there things that are missing in the graph?

**Comment by quasiben** [comment]
Many of the nodes have `into.foo`

**Comment by cpcloud** [comment]
Oh well that simply won't foo :)

**Comment by mrocklin** [comment]
I can handle this if no one else is.

**Comment by mrocklin** [comment]
Or rather, I'm on this.  Let me know if I'm overlapping.  Mostly this just
involves creating an environment with *everything* in it, running

from odo.dot import dot_graph
dot_graph()

And then saving files to the appropriate places in the repository.

**Comment by mrocklin** [comment]
Fixed by https://github.com/ContinuumIO/odo/commit/2f4c7fce02b9974b3eaaae8a32f6a678606e9ede
