### ISSUE TITLE
odo version is incorrect

### ISSUE THREAD

**Issue by aterrel** [ContinuumIO/odo#133]
Looks like release 3.0 and master think the version is 0.2.0

See: https://github.com/ContinuumIO/odo/blob/master/odo/__init__.py#L67

**Comment by mrocklin** [comment]
Thanks for reporting this.  We're going through a release cycle in the next couple days so hopefully this will be cleaned up soon.

**Comment by cpcloud** [comment]
closed by https://github.com/ContinuumIO/odo/commit/7041098d711f8ed4de5e0edebfec18e8365b9413
