### ISSUE TITLE
`NotImplementedError` vs `NotImplemented`

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/odo#134]
Maybe I'm missing something, but why does Odo detect and reroute on `NotImplementedError` instead of `NotImplemented`?

Python docs [advise](https://docs.python.org/3/library/exceptions.html#NotImplementedError) raising `NotImplementError` from abstract methods that are supposed to be overwritten by derived classes.

[`NotImplemented`](https://docs.python.org/2/library/constants.html#NotImplemented) is intended for "rich comparisons" and choosing which object should handle these comparisons.

Odo's path choosing seems to be more analogous to the latter rather than the former. So maybe backends should return `NotImplemented` instead of raising `NotImplementedError`. This might benefit performance slightly too, since raising and catching exceptions probably incurs more overhead than returning and checking constants.

**Comment by mrocklin** [comment]
Hrm, that does make sense.  One thing I'll say in defense of raising `NotImplementedError` is that it is kind of nice to just drop out of whatever control structure you were in.  Sometimes convert functions call convert functions and checking for a sentinel value like `NotImplemented` might become a bit hairy.  Still, I'm not opposed to this change.

**Comment by cpcloud** [comment]
closing for now as low priority, can revisit later if there's a strong reason too
