### ISSUE TITLE
API/BUG: a bogus uri should not create a file

### ISSUE THREAD

**Issue by jreback** [ContinuumIO/odo#180]
e.g.

``odo('hdfstore:foo.hdf5:://oc',data)``

will actually create a file 'hdfstore:foo.hdf5' and try the ``h5py`` conversion.

I think it would be reasonable safe to have the URI parser check for ':' and '/' at the head and raise a ``ValueError``

**Comment by cpcloud** [comment]
i think we just need a stricter regex here
