### ISSUE TITLE
Option[String] exception converting to numpy types

### ISSUE THREAD

**Issue by octophat** [ContinuumIO/odo#233]
I'm running into a NotNumpyCompatible exception in trying to convert a CSV to a Pandas DataFrame that I don't think is quite right. The CSV was converted from a Teradata table which assigned it the following DataShape:

```
var * {  
  ACCT_ID: ?int64,  
  SVC_OWNR_CD: ?string[6, 'A'],  
  SVC_OWNR_LOB_CD: ?string[4, 'A'],  
  RWRDS_ENRLMT_IND: ?string[1, 'A'],  
  ANUL_FEE_AMT: ?float64,  
  BRNDD_PROD_ID: ?int64,  
  BRNDD_PROD_ID_PROD_NM: ?string['A'],  
  PROD_NM: ?string['A'],  
  PROD_DT: ?date,  
  EDW_PUBLN_ID: ?int64,  
  floattest: ?float64  
  }
```

I'm working on extending odo to Teradata, so the DataShape reflects conversions from nullable CHAR and VARCHAR SQL types, among others.

A partial traceback is below, but it seems to me that the unit_to_dtype function in numpy_dtype isn't properly identifying strings inside of Option instances. Specifically, the [line](https://github.com/ContinuumIO/odo/blob/master/odo/numpy_dtype.py#L27) `if isinstance(ds, Option) and ds.ty in (date_, datetime_, string):`, which should pull the ty attribute out and essentially "de-Option-ize" the type, doesn't seem to trigger. Unless I'm mistaken about the purpose of this logic, it seems designed to pull the string out of the option for numpy.

The following bastardized version of the unit_to_dtype logic shows how looking for instances of the String class find the string types inside options, but the current logic using an in expression does not.

#### Existing logic
```
def fake_unit_to_dtype(ds):
    if isinstance(ds, datashape.Option) and ds.ty in (datashape.date_, datashape.datetime_, datashape.string):
        print 'Swapping out ds {0} for ds.ty {1}'.format(ds, ds.ty)
    else:
        print 'Not happening for ds {}.'.format(ds)
for name, typ in dshape.measure.dict.items():
    if not 'date' in str(typ):
        #print odo.numpy_dtype.unit_to_dtype(typ)
        fake_unit_to_dtype(typ)
```

```
Not happening for ds ?int64.
Not happening for ds ?int64.
Not happening for ds ?string['A'].
Not happening for ds ?string[6, 'A'].
Not happening for ds ?string[4, 'A'].
Not happening for ds ?string[1, 'A'].
Not happening for ds ?float64.
Not happening for ds ?int64.
Not happening for ds ?string['A'].
Not happening for ds ?float64.
```

--------

#### Modified logic
```
def fake_unit_to_dtype(ds):
    if isinstance(ds, datashape.Option) and isinstance(ds.ty, datashape.String):
        print 'Swapping out ds {0} for ds.ty {1}'.format(ds, ds.ty)
    else:
        print 'Not happening for ds {}.'.format(ds)
for name, typ in dshape.measure.dict.items():
    if not 'date' in str(typ):
        #print odo.numpy_dtype.unit_to_dtype(typ)
        fake_unit_to_dtype(typ)
```

```
Not happening for ds ?int64.
Not happening for ds ?int64.
Swapping out ds ?string['A'] for ds.ty string['A']
Swapping out ds ?string[6, 'A'] for ds.ty string[6, 'A']
Swapping out ds ?string[4, 'A'] for ds.ty string[4, 'A']
Swapping out ds ?string[1, 'A'] for ds.ty string[1, 'A']
Not happening for ds ?float64.
Not happening for ds ?int64.
Swapping out ds ?string['A'] for ds.ty string['A']
Not happening for ds ?float64.
```

**Is this expected behavior or a bug?**

(more traceback details below as promised)

```---------------------------------------------------------------------------
NotNumpyCompatible                        Traceback (most recent call last)
<ipython-input-24-ea1538c00b12> in <module>()
----> 1 dtypes, parse_dates = odo.numpy_dtype.dshape_to_pandas(dshape)

c:\Users\ZEQ837\AppData\Local\Continuum\Anaconda\lib\site-packages\odo\numpy_dtype.pyc in dshape_to_pandas(ds)
     78 
     79     dtypes = dict((name, unit_to_dtype(typ))
---> 80                   for name, typ in ds.measure.dict.items()
     81                   if not 'date' in str(typ))
     82 

c:\Users\ZEQ837\AppData\Local\Continuum\Anaconda\lib\site-packages\odo\numpy_dtype.pyc in <genexpr>((name, typ))
     79     dtypes = dict((name, unit_to_dtype(typ))
     80                   for name, typ in ds.measure.dict.items()
---> 81                   if not 'date' in str(typ))
     82 
     83     datetimes = [name for name, typ in ds.measure.dict.items()

c:\Users\ZEQ837\AppData\Local\Continuum\Anaconda\lib\site-packages\odo\numpy_dtype.pyc in unit_to_dtype(ds)
     29     if ds == string:
     30         return np.dtype('O')
---> 31     return to_numpy_dtype(ds)
     32 
     33 

c:\Users\ZEQ837\AppData\Local\Continuum\Anaconda\lib\site-packages\datashape\coretypes.pyc in to_numpy_dtype(ds)
   1185     """ Throw away the shape information and just return the
   1186     measure as NumPy dtype instance."""
-> 1187     return to_numpy(ds.measure)[1]
   1188 
   1189 

c:\Users\ZEQ837\AppData\Local\Continuum\Anaconda\lib\site-packages\datashape\coretypes.pyc in to_numpy(ds)
   1225     except AttributeError:
   1226         raise NotNumpyCompatible('DataShape measure %s is not NumPy-compatible'
-> 1227                                  % msr)
   1228 
   1229     if type(dtype) != np.dtype:

NotNumpyCompatible: DataShape measure ?string['A'] is not NumPy-compatible
```

**Comment by octophat** [comment]
`if isinstance(ds, datashape.Option) and isinstance(ds.ty, (type(datashape.date_), type(datashape.datetime_), type(datashape.string))):` is probably a better and more complete look for the modified logic. It picks up the string types and would also catch the date/datetime ones as well.

**Comment by cpcloud** [comment]
Yep. The issue here is that `datashape.string` is an instance of `datashape.String`, but so is every parameterized instance like `string[32, 'A']` or `string[4, 'U']` (`'U'` is the default). By only checking for `string` we lose the ability to identify the fixed length and different encoding strings.

**Comment by octophat** [comment]
Would you like me to do a pull request to fix this or do you have it? I think the fix is just the one line I posted in my comment.

Also, is there a forum or other place where development on odo is discussed? I and my company may be interested in contributing.

**Comment by cpcloud** [comment]
@octophat A pull request would be great! We discuss odo on the blaze dev mailing list. Here's a link: https://groups.google.com/a/continuum.io/forum/#!forum/blaze-dev

**Comment by octophat** [comment]
Alright, I've submited #246 to fix this - this fixed my issue and I was able to successfully convert a Teradata table to a DataFrame through a temporary CSV. :)

@cpcloud, I'll check out the mailing list, thanks. I'll also be at PyData Seattle next month and will try to catch up with you there as well.

**Comment by cpcloud** [comment]
@octophat Excellent! Thanks.
