### ISSUE TITLE
adding a few simple test cases

### ISSUE THREAD

**Issue by ywang007** [ContinuumIO/odo#251]
Hi, I would like to add a few simple tests for a couple files, namely:
append.py
utils.py

**Comment by cpcloud** [comment]
@ywang007 great! what did you have in mind? do you need help with something in particular?

**Comment by ywang007** [comment]
It's really more for me to get familiar with the github workflow. :)
I've made the change, raising the PR now.

**Comment by cpcloud** [comment]
closed by #252

**Comment by cpcloud** [comment]
@ywang007 useful github tip:

when you write

```
closes #some-issue-number
```
in the main message of the pull request, github will automagically closed the referenced issue number when the PR is merged

**Comment by ywang007** [comment]
@cpcloud , cool. i'll try that next time. thanks.
