### ISSUE TITLE
Where clause for SQL

### ISSUE THREAD

**Issue by mathnode** [ContinuumIO/odo#269]
Hi,

Where should I be specifying where clauses when the source is an SQL RDBMS? Is that possible?

Something like ```odo(source, employee_id>=10, '/tmp/new_employees.csv')``` ?

**Comment by mathnode** [comment]
I have answered my own question.

Use a blaze.Data object as the source, and blaze queries. http://blaze.pydata.org/en/latest/queries.html

**Comment by cpcloud** [comment]
thanks for asking questions!
